### ISSUE TITLE
Update POM Repository Reference to the Atlassian Consolidated Proxy URL

### ISSUE THREAD

**Issue by jtolotta** [katalon-studio/katalon-studio-jira-plugin#21]
The project fails to build with a message stating the `com.atlassian.platform:platform:pom:3.1.7 ` package cannot be downloaded. 

**Solution:** Update the repository to the following Atlassian consolidated proxy URL.
```
	<repositories>
		<repository>
			<id>atlassian-repo</id>
			<name>atlassian public repo</name>
			<url>https://packages.atlassian.com/mvn/maven-external/</url>
		</repository>
	</repositories>
```

Refer to [Jira-rest-java-client-core 5.1.* and fugue 2.7.0 breaks build because of missing dependencies](https://community.atlassian.com/t5/Jira-questions/Jira-rest-java-client-core-5-1-and-fugue-2-7-0-breaks-build/qaq-p/1151091) on [Atlassian Community](https://community.atlassian.com/) for more details

**Comment by duyluonganh** [comment]
@jtolotta 
We are updated in this: https://github.com/katalon-studio/katalon-studio-jira-plugin/pull/28 pull request. Thanks for your suggestion.
